/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import MainClasses.Controller;
import Utilities.HttpConnection;
import javax.swing.JOptionPane;
/**
 *
 * @author xbarn
 */
public class AdminFrame extends javax.swing.JFrame {
    HttpConnection conn;
    Controller controller;

    public Controller getController() {
        return controller;
    }

    public void setController(Controller con) {
        this.controller = con;
    }
    public HttpConnection getConn() {
        return conn;
    }

    public void setConn(HttpConnection conn) {
        this.conn = conn;
    }
    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        but_logout = new javax.swing.JButton();
        btn_conexions = new javax.swing.JButton();
        btn_blackList = new javax.swing.JButton();
        btn_conex_pais = new javax.swing.JButton();
        btn_usuari = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        setName("adminFrame"); // NOI18N

        jPanel1.setLayout(null);

        but_logout.setBorderPainted(false);
        but_logout.setContentAreaFilled(false);
        but_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(but_logout);
        but_logout.setBounds(570, 480, 40, 50);

        btn_conexions.setBorderPainted(false);
        btn_conexions.setContentAreaFilled(false);
        btn_conexions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conexionsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_conexions);
        btn_conexions.setBounds(560, 270, 70, 50);

        btn_blackList.setBorderPainted(false);
        btn_blackList.setContentAreaFilled(false);
        btn_blackList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_blackListActionPerformed(evt);
            }
        });
        jPanel1.add(btn_blackList);
        btn_blackList.setBounds(560, 410, 70, 40);

        btn_conex_pais.setBorderPainted(false);
        btn_conex_pais.setContentAreaFilled(false);
        btn_conex_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conex_paisActionPerformed(evt);
            }
        });
        jPanel1.add(btn_conex_pais);
        btn_conex_pais.setBounds(570, 340, 70, 40);

        btn_usuari.setBorderPainted(false);
        btn_usuari.setContentAreaFilled(false);
        btn_usuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariActionPerformed(evt);
            }
        });
        jPanel1.add(btn_usuari);
        btn_usuari.setBounds(560, 200, 80, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/logo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 20, 190, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\xbarn\\Documents\\IOC\\Projecte\\Imatges\\Backgrounds\\2.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -50, 1610, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1277, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     /**
     * Click per a logout del server. 
     */
    private void but_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_logoutActionPerformed

        //Si cliquem al button de tanca sessió, tanquem sessió. 
        this.conn.logOut();
        System.exit(0);
        
    }//GEN-LAST:event_but_logoutActionPerformed

     /**
     * Click en el butó del frame on es mostra les conexions en taula
     */
    
    private void btn_conexionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conexionsActionPerformed
                Conexions_table cf = new Conexions_table();
                cf.setContr(controller);
                cf.show();  
    }//GEN-LAST:event_btn_conexionsActionPerformed

     /**
     * Click en el butó del frame on es mostra les conexions per pais
     */
    
    private void btn_conex_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conex_paisActionPerformed
        Conexions_graph cg = new Conexions_graph();
        cg.setContr(controller);
        cg.show();
    }//GEN-LAST:event_btn_conex_paisActionPerformed
    /**
     * Click en el butó del frame on es mostra la blacklist
     */
    private void btn_blackListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_blackListActionPerformed
        BlackList_frame blck_list = new BlackList_frame();
        blck_list.show();
    }//GEN-LAST:event_btn_blackListActionPerformed
    /**
     * Click en el butó del frame on es mostra les dades d'usuari.
     */
    private void btn_usuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariActionPerformed
        if (this.controller.getUser().isAdmin()) {
            //En aquesta acció mostrem el frame amb les dades d'usuari que seleccioni. 
            // Li passem l'objecte user i el controller. 
            PersonalData_Frame pf = new PersonalData_Frame(this.controller, this.controller.getUser());
            pf.show();
        } else {
            //Creem el message d'informació login error
            JOptionPane.showMessageDialog(null, "AQUESTA OPCIO ES NOMES VALIDA PER ADMINS", "INCORRECT ROLE", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btn_usuariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //Creem la form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_blackList;
    private javax.swing.JButton btn_conex_pais;
    private javax.swing.JButton btn_conexions;
    private javax.swing.JButton btn_usuari;
    private javax.swing.JButton but_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
