/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author xbarn
 */
import MainClasses.Controller;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        but_Login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tx_username = new java.awt.TextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1250, 700));
        setMinimumSize(new java.awt.Dimension(1250, 700));
        getContentPane().setLayout(null);

        but_Login.setBackground(new java.awt.Color(0, 0, 0));
        but_Login.setBorderPainted(false);
        but_Login.setContentAreaFilled(false);
        but_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(but_Login);
        but_Login.setBounds(470, 410, 340, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 40, 200, 90);

        tx_username.setBackground(new java.awt.Color(0, 0, 0));
        tx_username.setForeground(new java.awt.Color(255, 255, 255));
        tx_username.setText("Username");
        tx_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tx_usernameMouseClicked(evt);
            }
        });
        tx_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(tx_username);
        tx_username.setBounds(470, 310, 340, 30);

        jPasswordField1.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setText("Password");
        jPasswordField1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(470, 360, 340, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\xbarn\\Documents\\login_screen2.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1230, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //On click on the button login, let's check username , ... 
    private void but_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_LoginActionPerformed
        
        //Get the values of the username and password and send it to the class controller
        String passw = this.jPasswordField1.getText();
        String username = this.tx_username.getText();
        
        boolean isValid;
        Controller contr = new Controller();
        //Creem un objecte controller i li passem al constructor la password i el usuari per a comprovar les credencials. 
        contr.setController(username,passw);
        isValid = contr.isValid();
        
        if (isValid) {
            //Is valid, but is it an admin or is it an user? 
            if (contr.getUser().isAdmin()) {
                AdminFrame af = new AdminFrame();
                af.show();
                af.setConn(contr.getConn());
                af.setController(contr);
                dispose();
            } else {
                UserFrame uf = new UserFrame();
                uf.show();
                uf.setConn(contr.getConn());
                uf.setController(contr);
                dispose();
            }
        } else {
            //Creem el message d'informació login error
            JOptionPane.showMessageDialog(null, "INCORRECT USERNAME OR PASSWORD", "INCORRECT VALIDATION", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_but_LoginActionPerformed

    private void tx_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_usernameActionPerformed
        this.tx_username.setText("");
    }//GEN-LAST:event_tx_usernameActionPerformed

    private void tx_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx_usernameMouseClicked
        this.tx_username.setText("");
    }//GEN-LAST:event_tx_usernameMouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        this.jPasswordField1.setText("");

    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        this.jPasswordField1.setText("");

    }//GEN-LAST:event_jPasswordField1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private java.awt.TextField tx_username;
    // End of variables declaration//GEN-END:variables
}
